# Generated by Django 4.2.30 on 2026-05-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_page_block_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAgentWebhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(max_length=2048)),
                ('secret_encrypted', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Workspace Agent Webhook',
                'verbose_name_plural': 'Workspace Agent Webhooks',
                'db_table': 'workspace_agent_webhooks',
            },
        ),
        migrations.RenameIndex(
            model_name='pageblockcomment',
            new_name='page_block__page_id_fdee0a_idx',
            old_name='page_block_idx',
        ),
        migrations.RenameIndex(
            model_name='pageblockcomment',
            new_name='page_block__page_id_6e0e3b_idx',
            old_name='page_resolved_idx',
        ),
        migrations.AlterField(
            model_name='pageblockcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='workspaceagentwebhook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workspaceagentwebhook',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workspaceagentwebhook',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_webhook', to='db.workspace'),
        ),
    ]
