# Generated by Django 4.2.30 on 2026-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_workspace_agent_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('doc', 'Doc'), ('diagram', 'Diagram'), ('whiteboard', 'Whiteboard')], default='doc', max_length=16),
        ),
    ]
