# Generated by Django 4.2.30 on 2026-05-19 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.agent
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_user_calendar_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=2048)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('provider_model', models.CharField(blank=True, default='', max_length=128)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('api_base_url', models.URLField(blank=True, default='', max_length=2048)),
                ('triggers', models.JSONField(default=plane.db.models.agent._default_triggers)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_concurrent_runs', models.PositiveSmallIntegerField(default=3)),
                ('draft_mode', models.BooleanField(default=False)),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trigger_event', models.CharField(choices=[('assigned', 'Assigned'), ('mentioned', 'Mentioned'), ('state_change', 'State change'), ('comment', 'Comment'), ('manual', 'Manual')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='db.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'db_table': 'agent_runs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', 'status'], name='agent_runs_agent_i_215b8b_idx'), models.Index(fields=['issue', 'agent'], name='agent_runs_issue_i_d277f1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'bot_user'), name='agent_unique_workspace_bot_user_when_deleted_at_null'),
        ),
    ]
