# Generated by Django 4.2.30 on 2026-05-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_workspace_llm_api_key_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='iterations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
