# Generated by Django 4.2.30 on 2026-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_agent_run_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pageblockcomment',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
