# Generated by Django 4.2.30 on 2026-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_agent_drafts_and_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mcp_servers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
