# Generated by Django 4.2.30 on 2026-05-21 02:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0139_issuerelation_custom_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('default_name', models.CharField(blank=True, default='', max_length=255)),
                ('default_description_html', models.TextField(blank=True, default='<p></p>')),
                ('default_priority', models.CharField(blank=True, default='', max_length=30)),
                ('default_assignee_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('default_label_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Work Item Template',
                'verbose_name_plural': 'Work Item Templates',
                'db_table': 'work_item_templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='agentchatmessage',
            new_name='agent_chat__session_a23c63_idx',
            old_name='agent_chat__session_2d4bee_idx',
        ),
        migrations.RenameIndex(
            model_name='agentchatsession',
            new_name='agent_chat__workspa_48fa2f_idx',
            old_name='agent_chat_workspac_06fdda_idx',
        ),
        migrations.RenameIndex(
            model_name='pagetemplate',
            new_name='page_templa_workspa_30a614_idx',
            old_name='pagetemplate_ws_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttemplate',
            new_name='project_tem_workspa_edf5bb_idx',
            old_name='project_tem_workspac_a6b3f1_idx',
        ),
        migrations.AlterField(
            model_name='agentchatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='agentchatmessage',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agentchatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='agentchatsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='agentchatsession',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agentchatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AddField(
            model_name='workitemtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workitemtemplate',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemtemplate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workitemtemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_templates', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='workitemtemplate',
            index=models.Index(fields=['workspace', '-created_at'], name='work_item_t_workspa_8657b5_idx'),
        ),
    ]
