# Generated by Django 5.2.2 on 2026-05-22

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0140_work_item_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceAIConnector",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("external_workspace_id", models.CharField(max_length=255)),
                ("external_workspace_name", models.CharField(blank=True, max_length=255)),
                ("external_user_id", models.CharField(max_length=255)),
                ("provider", models.CharField(choices=[("claude", "Claude"), ("chatgpt", "ChatGPT"), ("openclaw", "OpenClaw"), ("hermes", "Hermes")], max_length=32)),
                ("auth_mode", models.CharField(choices=[("oauth", "OAuth"), ("api_key", "API key"), ("token", "Token")], max_length=32)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("revoked", "Revoked"), ("error", "Error")], default="active", max_length=16)),
                ("secret_encrypted", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("last_synced_at", models.DateTimeField(null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_ai_connectors", to="db.user")),
                ("default_project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_connectors", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_connectors", to="db.workspace")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspaceaiconnector_created_by", to="db.user")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspaceaiconnector_updated_by", to="db.user")),
            ],
            options={"db_table": "workspace_ai_connectors", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AIConnectorEvent",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source_message_id", models.CharField(max_length=255)),
                ("dedupe_key", models.CharField(max_length=512)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("received", "Received"), ("processing", "Processing"), ("processed", "Processed"), ("failed", "Failed")], max_length=16)),
                ("error", models.TextField(blank=True, null=True)),
                ("connector", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="db.workspaceaiconnector")),
                ("created_issue", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.issue")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_connector_events", to="db.workspace")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="aiconnectorevent_created_by", to="db.user")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="aiconnectorevent_updated_by", to="db.user")),
            ],
            options={"db_table": "ai_connector_events", "ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="workspaceaiconnector",
            constraint=models.UniqueConstraint(
                condition=Q(("deleted_at__isnull", True)),
                fields=("workspace", "provider", "external_workspace_id", "external_user_id"),
                name="workspace_ai_connector_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiconnectorevent",
            constraint=models.UniqueConstraint(
                condition=Q(("deleted_at__isnull", True)),
                fields=("connector", "source_message_id"),
                name="ai_connector_event_unique_source_message",
            ),
        ),
    ]
