# Generated by Codex on 2026-05-22

from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.agent
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0141_ai_workspace_connectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="tool_policies",
            field=models.JSONField(default=plane.db.models.agent._default_tool_policies),
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.CharField(max_length=160)),
                ("value", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="db.agent",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memories",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Memory",
                "verbose_name_plural": "Agent Memories",
                "db_table": "agent_memories",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(fields=["workspace", "agent", "key"], name="agent_memor_workspa_703f5f_idx"),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(fields=["workspace", "-updated_at"], name="agent_memor_workspa_5d8db9_idx"),
        ),
    ]
