# Generated by Codex on 2026-05-22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0142_agent_tool_policies_and_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAutomation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[("issue_created", "Issue created")],
                        default="issue_created",
                        max_length=32,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automations",
                        to="db.agent",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_automations",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Automation",
                "verbose_name_plural": "Agent Automations",
                "db_table": "agent_automations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="agentautomation",
            index=models.Index(
                fields=["workspace", "is_enabled", "trigger_event"],
                name="agent_autom_workspa_865cfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentautomation",
            index=models.Index(fields=["agent", "is_enabled"], name="agent_autom_agent_i_3074a4_idx"),
        ),
    ]
