# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0144_project_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="access",
            field=models.PositiveSmallIntegerField(choices=((0, "Public"), (1, "Private")), default=1),
        ),
    ]
