# Generated by Django 4.2.21 on 2026-05-25 22:30

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0145_page_default_private_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCustomField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("select", "Select"),
                            ("multi_select", "Multi Select"),
                        ],
                        default="text",
                        max_length=40,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.FloatField(default=65535)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projectcustomfield_created_by",
                        to="db.user",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_projectcustomfield",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projectcustomfield_updated_by",
                        to="db.user",
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_projectcustomfield",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Custom Field",
                "verbose_name_plural": "Project Custom Fields",
                "db_table": "project_custom_fields",
                "ordering": ("sort_order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="projectcustomfield",
            constraint=models.UniqueConstraint(
                condition=Q(("deleted_at__isnull", True)),
                fields=("project", "name"),
                name="project_custom_field_unique_project_name_when_deleted_at_null",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="custom_field_values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
