# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0149_rename_home_preference_on_my_plate_to_my_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[("doc", "Doc"), ("whiteboard", "Whiteboard"), ("pdf", "PDF")],
                default="doc",
                max_length=16,
            ),
        ),
    ]
