# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0154_canonicalize_agent_name_atlas"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="composio_api_key_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="composio_base_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="composio_toolkits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="composio_allow_write_tools",
            field=models.BooleanField(default=False),
        ),
    ]
