# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0156_sticky_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_brief",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
