# Generated by Claude

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0160_migrate_automations_to_workflows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("doc", "Doc"),
                    ("whiteboard", "Whiteboard"),
                    ("pdf", "PDF"),
                    ("sheet", "Sheet"),
                ],
                default="doc",
                max_length=16,
            ),
        ),
    ]
