# Generated by Claude

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0161_page_sheet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("doc", "Doc"),
                    ("whiteboard", "Whiteboard"),
                    ("pdf", "PDF"),
                    ("sheet", "Sheet"),
                    ("folder", "Folder"),
                ],
                default="doc",
                max_length=16,
            ),
        ),
    ]
