# Generated by Codex on 2026-07-23

from django.db import migrations


def disable_legacy_issue_created_trigger(apps, schema_editor):
    Agent = apps.get_model("db", "Agent")

    for agent in Agent.objects.all().only("id", "triggers").iterator():
        triggers = dict(agent.triggers or {})
        if triggers.get("issue_created") is False:
            continue
        triggers["issue_created"] = False
        Agent.objects.filter(pk=agent.pk).update(triggers=triggers)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0164_page_version_page_type"),
    ]

    operations = [
        migrations.RunPython(disable_legacy_issue_created_trigger, migrations.RunPython.noop),
    ]
