# Generated by Codex on 2026-08-15

import uuid

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0165_disable_legacy_issue_created_agent_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContextSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("provider", models.CharField(choices=[("google_drive", "Google Drive"), ("manual", "Manual import")], max_length=32)),
                ("root_external_id", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("stale", "Stale"), ("error", "Error"), ("disconnected", "Disconnected")], default="pending", max_length=24)),
                ("selection_config", models.JSONField(blank=True, default=dict)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="context_sources", to="db.project")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_context_sources", to="db.workspace")),
            ],
            options={
                "verbose_name": "Project Context Source",
                "verbose_name_plural": "Project Context Sources",
                "db_table": "project_context_sources",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectSourceFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("external_id", models.CharField(max_length=255)),
                ("relative_path", models.CharField(max_length=1024)),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("is_eligible", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, default="", max_length=96)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="files", to="db.projectcontextsource")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
            ],
            options={
                "verbose_name": "Project Source File",
                "verbose_name_plural": "Project Source Files",
                "db_table": "project_source_files",
                "ordering": ("relative_path",),
            },
        ),
        migrations.CreateModel(
            name="ProjectSourceRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("provider_revision", models.CharField(blank=True, default="", max_length=255)),
                ("content_hash", models.CharField(max_length=64)),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("is_truncated", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("source_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="db.projectsourcefile")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
            ],
            options={
                "verbose_name": "Project Source Revision",
                "verbose_name_plural": "Project Source Revisions",
                "db_table": "project_source_revisions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="projectcontextsource",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("project", "provider", "root_external_id"), name="project_context_source_unique_root_when_active"),
        ),
        migrations.AddIndex(
            model_name="projectcontextsource",
            index=models.Index(fields=["workspace", "project", "status"], name="project_con_workspa_999d34_idx"),
        ),
        migrations.AddIndex(
            model_name="projectcontextsource",
            index=models.Index(fields=["workspace", "provider"], name="project_con_workspa_186a65_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectsourcefile",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("source", "external_id"), name="project_source_file_unique_external_when_active"),
        ),
        migrations.AddConstraint(
            model_name="projectsourcefile",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("source", "relative_path"), name="project_source_file_unique_path_when_active"),
        ),
        migrations.AddIndex(
            model_name="projectsourcefile",
            index=models.Index(fields=["source", "is_eligible"], name="project_sou_source__142760_idx"),
        ),
        migrations.AddIndex(
            model_name="projectsourcefile",
            index=models.Index(fields=["source", "relative_path"], name="project_sou_source__0b1080_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectsourcerevision",
            constraint=models.UniqueConstraint(fields=("source_file", "content_hash"), name="project_source_revision_unique_content_hash"),
        ),
        migrations.AddIndex(
            model_name="projectsourcerevision",
            index=models.Index(fields=["source_file", "-created_at"], name="project_sou_source__504dd5_idx"),
        ),
    ]
