# Generated by Django 4.2.30 on 2026-08-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0166_project_context_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContextConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(choices=[("google_drive", "Google Drive")], max_length=32)),
                ("account_email", models.EmailField(blank=True, max_length=254)),
                ("access_token_encrypted", models.TextField()),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_context_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_context_connections",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Context Connection",
                "verbose_name_plural": "Project Context Connections",
                "db_table": "project_context_connections",
            },
        ),
        migrations.AddField(
            model_name="projectcontextsource",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="db.projectcontextconnection",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcontextconnection",
            index=models.Index(
                fields=["workspace", "user", "provider", "is_active"], name="project_con_workspa_0bc2b7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcontextconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "user", "provider", "account_email"),
                name="project_context_connection_unique_account_when_active",
            ),
        ),
    ]
