/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 *
 * Lucide -> Phosphor shim.
 *
 * Phosphor (light weight) is the icon set for DragonFruit. To avoid touching
 * every call site twice (once to migrate, again to tweak), code keeps importing
 * by Lucide names; this shim re-exports the matching Phosphor icons under
 * those names. Global `weight="light"` is set via IconContext.Provider at the
 * app root, so no per-component prop changes are needed.
 *
 * If a name is missing here, add it: find the closest Phosphor icon at
 * https://phosphoricons.com/ and alias it below.
 */

export type { Icon as LucideIcon, IconProps as LucideProps } from "@phosphor-icons/react";

export {
  // ── identity (same name in both libraries) ────────────────────────────
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Briefcase,
  Building,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle,
  Circle,
  CircleDashed,
  Clipboard,
  Clock,
  CreditCard,
  Crown,
  Dot,
  Download,
  Eraser,
  Eye,
  EyeClosed,
  File,
  FileText,
  Folder,
  FolderPlus,
  Info,
  Lightbulb,
  Link,
  Microscope,
  Minus,
  MinusCircle,
  Monitor,
  Network,
  Palette,
  Paperclip,
  Pencil,
  Plus,
  Rocket,
  Shapes,
  Share,
  SlidersHorizontal,
  Sparkle,
  Star,
  ToggleRight,
  Triangle,
  User,

  // ── aliased mappings ──────────────────────────────────────────────────
  TextAa as ALargeSmall,
  ChartLineUp as Activity,
  WarningCircle as AlertCircle,
  WarningOctagon as AlertOctagon,
  Warning as AlertTriangle,
  Warning as AlertTriangleIcon,
  Warning as TriangleAlert,
  WarningOctagon as OctagonAlert,
  WarningCircle as CircleAlert,
  TextAlignCenter as AlignCenter,
  TextAlignLeft as AlignLeftIcon,
  TextAlignRight as AlignRightIcon,
  Archive as ArchiveIcon,
  ArrowsClockwise as ArchiveRestore,
  ArrowsClockwise as ArchiveRestoreIcon,
  X as ArchiveX,
  SortAscending as ArrowDownWideNarrow,
  ArrowCircleRight as ArrowRightCircle,
  Swap as ArrowRightLeft,
  SortDescending as ArrowUpNarrowWide,
  ArrowLineUp as ArrowUpToLine,
  SortAscending as ArrowUpWideNarrow,
  At as AtSign,
  Prohibit as Ban,
  ChartBar as BarChart2,
  ChartBar as BarChart4,
  ChartBar as ChartNoAxesColumn,
  BellSlash as BellOff,
  Cube as Box,
  Cube as Boxes,
  CalendarDots as CalendarDays,
  Check as CheckCheck,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretUpDown as ChevronsUpDown,
  CircleHalf as CircleDot,
  CircleDashed as CircleDotDashed,
  PlusCircle as CirclePlus,
  UserCircle as CircleUser,
  UserCircle as CircleUserRound,
  XCircle as CircleX,
  CheckCircle as CircleCheck,
  ArrowCircleUp as CircleArrowUp,
  CloudSlash as CloudOff,
  Cube as Component,
  ArrowBendDownRight as CornerDownRight,
  PencilSimple as Edit,
  DotsThree as Ellipsis,
  DotsThreeVertical as EllipsisVertical,
  ArrowsOut as Expand,
  ArrowSquareOut as ExternalLink,
  EyeSlash as EyeOff,
  Eye as EyeIcon,
  File as FileIcon,
  FileArrowUp as FileOutput,
  Files as FileStack,
  GithubLogo as GithubIcon,
  GridFour as GridIcon,
  DotsSixVertical as GripVertical,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  House as Home,
  Buildings as Hotel,
  Image as ImageIcon,
  Tray as Inbox,
  Info as InfoIcon,
  Key as KeyRound,
  Translate as Languages,
  Stack as Layers,
  Stack as Layers2,
  Stack as LayersIcon,
  SquaresFour as LayoutGrid,
  LinkBreak as Link2Off,
  CircleNotch as Loader,
  CircleNotch as Loader2,
  Lock as LockIcon,
  Lock as LockKeyhole,
  LockKeyOpen as LockKeyholeOpen,
  SignOut as LogOut,
  Envelope as Mail,
  EnvelopeSimple as Mails,
  ArrowsOutSimple as Maximize,
  ArrowsOutSimple as Maximize2,
  List as Menu,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  ArrowsInSimple as Minimize2,
  DotsThree as MoreHorizontal,
  DotsThreeVertical as MoreVertical,
  DotsThreeVertical as MoreVerticalIcon,
  ArrowsOutCardinal as MoveDiagonal,
  ArrowsLeftRight as MoveHorizontal,
  ArrowLeft as MoveLeft,
  ArrowRight as MoveRight,
  Sidebar as PanelLeft,
  SidebarSimple as PanelRight,
  PencilLine as PenSquare,
  PenNib as PenTool,
  PushPin as Pin,
  PushPinSlash as PinOff,
  ArrowsCounterClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  Gear as Settings,
  Sliders as Settings2,
  Gear as SettingsIcon,
  ShareNetwork as Share2,
  ArrowsIn as Shrink,
  CellSignalHigh as SignalHigh,
  CellSignalLow as SignalLow,
  CellSignalMedium as SignalMedium,
  SmileyWink as SmilePlus,
  Sparkle as Sparkles,
  PlusSquare as SquarePlus,
  Stack as SquareStackIcon,
  IdentificationBadge as SquareUser,
  StarHalf as StarOff,
  Note as StickyIcon,
  Note as StickyNote,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  TextT as Type,
  CloudArrowUp as UploadCloud,
  User as User2,
  UserPlus,
  User as UserRound,
  Users,
  MagicWand as Wand2,
  WebhooksLogo as Webhook,
  X,
  XCircle,
  X as XIcon,
  Lightning as Zap,
  MinusCircle as CircleMinus,
  Globe as Earth,
  Funnel as ListFilter,
  Funnel as ListFilterPlus,
  Trash as Trash2,

  // ── editor & text-formatting ──────────────────────────────────────────
  TextB as Bold,
  TextItalic as Italic,
  TextUnderline as Underline,
  TextStrikethrough as Strikethrough,
  TextAa as CaseSensitive,
  Code as Code2,
  Quotes as TextQuote,
  TextHOne as Heading1,
  TextHTwo as Heading2,
  TextHThree as Heading3,
  TextHFour as Heading4,
  TextHFive as Heading5,
  TextHSix as Heading6,
  List,
  ListNumbers as ListOrdered,
  ListChecks as ListTodo,
  Table,
  Image,
  Hash,
  Tag as TagIcon,
  Timer,

  // ── icons with `-Icon` suffix in caller code ──────────────────────────
  Triangle as TriangleIcon,
  SquaresFour as LayoutGridIcon,
  Link as Link2Icon,
  Chat as MessageSquareIcon,
  Paperclip as PaperclipIcon,
  Users as Users2Icon,
  Users as UsersIcon,

  // ── misc ──────────────────────────────────────────────────────────────
  CellSignalFull as Signal,
  CellSignalMedium as SignalMediumIcon,
  CopySimple as CopyPlus,
  GitBranch,
  Ticket as TicketCheck,
  UserMinus as UserMinus2,
  UserPlus as UserPlus2,
} from "@phosphor-icons/react";
